//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSMTP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSMTP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Address CC.
        /// </summary>
        public static string CMenuCopyCC {
            get {
                return ResourceManager.GetString("CMenuCopyCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Date.
        /// </summary>
        public static string CMenuCopyDate {
            get {
                return ResourceManager.GetString("CMenuCopyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Address From.
        /// </summary>
        public static string CMenuCopyFrom {
            get {
                return ResourceManager.GetString("CMenuCopyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CMenuCopyMessage {
            get {
                return ResourceManager.GetString("CMenuCopyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RAW _data.
        /// </summary>
        public static string CMenuCopyRAW {
            get {
                return ResourceManager.GetString("CMenuCopyRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Address Reply To.
        /// </summary>
        public static string CMenuCopyReplyTo {
            get {
                return ResourceManager.GetString("CMenuCopyReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Subject.
        /// </summary>
        public static string CMenuCopySubject {
            get {
                return ResourceManager.GetString("CMenuCopySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy Address To.
        /// </summary>
        public static string CMenuCopyTo {
            get {
                return ResourceManager.GetString("CMenuCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Remove.
        /// </summary>
        public static string CMenuRemove {
            get {
                return ResourceManager.GetString("CMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESMTP.
        /// </summary>
        public static string ESMTP {
            get {
                return ResourceManager.GetString("ESMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status.
        /// </summary>
        public static string MessageBoxServerStatusHeader {
            get {
                return ResourceManager.GetString("MessageBoxServerStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is running in {0} mode.
        ///Stop the server?.
        /// </summary>
        public static string MessageBoxServerStatusRunning {
            get {
                return ResourceManager.GetString("MessageBoxServerStatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is stopped.
        ///Start the server?.
        /// </summary>
        public static string MessageBoxServerStatusStopped {
            get {
                return ResourceManager.GetString("MessageBoxServerStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP.
        /// </summary>
        public static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC: .
        /// </summary>
        public static string TitleMessageCC {
            get {
                return ResourceManager.GetString("TitleMessageCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: .
        /// </summary>
        public static string TitleMessageFrom {
            get {
                return ResourceManager.GetString("TitleMessageFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply To: .
        /// </summary>
        public static string TitleMessageReplyTo {
            get {
                return ResourceManager.GetString("TitleMessageReplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject: .
        /// </summary>
        public static string TitleMessageSubject {
            get {
                return ResourceManager.GetString("TitleMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: .
        /// </summary>
        public static string TitleMessageTo {
            get {
                return ResourceManager.GetString("TitleMessageTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change listening port.
        /// </summary>
        public static string TooltipChangePort {
            get {
                return ResourceManager.GetString("TooltipChangePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Messages.
        /// </summary>
        public static string TooltipClearMessages {
            get {
                return ResourceManager.GetString("TooltipClearMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable ESMTP.
        /// </summary>
        public static string TooltipEnableESMTP {
            get {
                return ResourceManager.GetString("TooltipEnableESMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSMTP Mailbox.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
